stages:
 - build
 - test

build:
  stage: build
  image: node:latest
  # only:
  #   - master
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build 
  artifacts:
    paths:
      - dist/
    expire_in: 2 days
  cache:
    paths:
      - node_modules/

test:
  image: trion/ng-cli-karma
  stage: test
  script:
    - yarn add @angular-devkit/build-angular --dev
    - ng test --no-watch --code-coverage
    - ng e2e
  artifacts:
    paths:
      - coverage/


