stages:
 - build
 - test
 - deploy

cache:
    paths:
      - node_modules/

build:
  stage: build
  image: node
  # only:
  #   - master    
  script:
    - npm ci
    - npm install -g @angular/cli
    - ng build 
  artifacts:
    paths:
      - dist/

test:
  image: trion/ng-cli-karma
  stage: test
  before_script:
    - yarn global add @angular/cli
    - yarn install
  script:
    - yarn add @angular-devkit/build-angular --dev
    - ng test --no-watch --code-coverage
    - ng e2e
  artifacts:
    paths:
      - coverage/

deploy:
  dependencies:
    - build
  image: docker:latest
  stage: deploy
  script:
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - docker build -t moviecupidon/frontend:latest .
      - docker tag moviecupidon/frontend:latest bayar4b/movie-cupidon-frontend:latest
      - docker push bayar4b/movie-cupidon-frontend:latest
  only:
    - master

